#!/bin/bash

#create a file to save the data
touch save-data
echo "Structure, Henry's Constant, error" >> save-data

#loop through each idealized structure
for((i=1;i<=10;i++))
do

#extracting folder name
file=$(awk 'FNR=='$i' {print $1}' files.txt)

#change of directories in order to access output file 
cd ${file}/Output/System_0

#declaration/initilization of variables
Henry=$(grep "Average Henry" *.data | awk 'FNR==2 {print $5}')
Err=$(grep "Average Henry" *.data | awk 'FNR==2 {print $7}')
echo $file, $Henry, $Err >> ../../../save-data

#change of directories prior to looping through another structure
cd ../../..
done
